[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# TTS合成

## vall\-e

### https://github\.com/lifeiteng/vall\-e

## gpt\-sovits

### https://github\.com/cbb9556/GPT\-SoVITS

## chat\-tts

### https://github\.com/2noise/ChatTTS

## mockingbird

### https://github\.com/cbb9556/MockingBird

## air\-vits

### https://github\.com/innnky/ar\-vits

## soundstorm

### https://github\.com/yangdongchao/SoundStorm

## 简单原理

### https://www\.zhihu\.com/question/26815523/answer/3408428177

### 也需要大量的训练资源

### 字节的声音复制很好，但是缺乏情感， 对一件事的表达缺乏灵性
